//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Uchet
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T действие.
    /// </summary>
    // *** Start programmer edit section *** (tДействие CustomAttributes)

    // *** End programmer edit section *** (tДействие CustomAttributes)
    public enum tДействие
    {
        
        // *** Start programmer edit section *** (tДействие.Установка CustomAttributes)

        // *** End programmer edit section *** (tДействие.Установка CustomAttributes)
        Установка,
        
        // *** Start programmer edit section *** (tДействие.Изменение CustomAttributes)

        // *** End programmer edit section *** (tДействие.Изменение CustomAttributes)
        Изменение,
    }
}
