//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Uchet
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Операции.
    /// </summary>
    // *** Start programmer edit section *** (Операции CustomAttributes)

    // *** End programmer edit section *** (Операции CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОперацииE", new string[] {
            "Дата as \'Дата\'",
            "Действие as \'Действие\'",
            "Состояние as \'Состояние\'",
            "Админ as \'Админ\'",
            "Админ.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Админ.ФИО"})]
    [MasterViewDefineAttribute("ОперацииE", "Админ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОперацииL", new string[] {
            "Дата as \'Дата\'",
            "Действие as \'Действие\'",
            "Состояние as \'Состояние\'",
            "Админ.ФИО as \'ФИО\'"})]
    public class Операции : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Uchet.tДействие fДействие;
        
        private IIS.Uchet.tСостояние fСостояние;
        
        private IIS.Uchet.Оборудование fОборудование;
        
        private IIS.Uchet.Пользователь fАдмин;
        
        // *** Start programmer edit section *** (Операции CustomMembers)

        // *** End programmer edit section *** (Операции CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Дата CustomAttributes)

        // *** End programmer edit section *** (Операции.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Дата Get start)

                // *** End programmer edit section *** (Операции.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Операции.Дата Get end)

                // *** End programmer edit section *** (Операции.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Дата Set start)

                // *** End programmer edit section *** (Операции.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Операции.Дата Set end)

                // *** End programmer edit section *** (Операции.Дата Set end)
            }
        }
        
        /// <summary>
        /// Действие.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Действие CustomAttributes)

        // *** End programmer edit section *** (Операции.Действие CustomAttributes)
        public virtual IIS.Uchet.tДействие Действие
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Действие Get start)

                // *** End programmer edit section *** (Операции.Действие Get start)
                IIS.Uchet.tДействие result = this.fДействие;
                // *** Start programmer edit section *** (Операции.Действие Get end)

                // *** End programmer edit section *** (Операции.Действие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Действие Set start)

                // *** End programmer edit section *** (Операции.Действие Set start)
                this.fДействие = value;
                // *** Start programmer edit section *** (Операции.Действие Set end)

                // *** End programmer edit section *** (Операции.Действие Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Состояние CustomAttributes)

        // *** End programmer edit section *** (Операции.Состояние CustomAttributes)
        public virtual IIS.Uchet.tСостояние Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Состояние Get start)

                // *** End programmer edit section *** (Операции.Состояние Get start)
                IIS.Uchet.tСостояние result = this.fСостояние;
                // *** Start programmer edit section *** (Операции.Состояние Get end)

                // *** End programmer edit section *** (Операции.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Состояние Set start)

                // *** End programmer edit section *** (Операции.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Операции.Состояние Set end)

                // *** End programmer edit section *** (Операции.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Операции.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Админ CustomAttributes)

        // *** End programmer edit section *** (Операции.Админ CustomAttributes)
        [PropertyStorage(new string[] {
                "Админ"})]
        [NotNull()]
        public virtual IIS.Uchet.Пользователь Админ
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Админ Get start)

                // *** End programmer edit section *** (Операции.Админ Get start)
                IIS.Uchet.Пользователь result = this.fАдмин;
                // *** Start programmer edit section *** (Операции.Админ Get end)

                // *** End programmer edit section *** (Операции.Админ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Админ Set start)

                // *** End programmer edit section *** (Операции.Админ Set start)
                this.fАдмин = value;
                // *** Start programmer edit section *** (Операции.Админ Set end)

                // *** End programmer edit section *** (Операции.Админ Set end)
            }
        }
        
        /// <summary>
        /// Операции.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Оборудование CustomAttributes)

        // *** End programmer edit section *** (Операции.Оборудование CustomAttributes)
        [PropertyStorage(new string[] {
                "Оборудование"})]
        [NotNull()]
        public virtual IIS.Uchet.Оборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Оборудование Get start)

                // *** End programmer edit section *** (Операции.Оборудование Get start)
                IIS.Uchet.Оборудование result = this.fОборудование;
                // *** Start programmer edit section *** (Операции.Оборудование Get end)

                // *** End programmer edit section *** (Операции.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Оборудование Set start)

                // *** End programmer edit section *** (Операции.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (Операции.Оборудование Set end)

                // *** End programmer edit section *** (Операции.Оборудование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОперацииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперацииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперацииE", typeof(IIS.Uchet.Операции));
                }
            }
            
            /// <summary>
            /// "ОперацииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперацииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперацииL", typeof(IIS.Uchet.Операции));
                }
            }
        }
    }
}
