//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Uchet
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ПО.
    /// </summary>
    // *** Start programmer edit section *** (ПО CustomAttributes)

    // *** End programmer edit section *** (ПО CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПОE", new string[] {
            "Название as \'Название\'",
            "Версия as \'Версия\'",
            "Freeware as \'Freeware\'",
            "Вендор as \'Вендор\'",
            "Вендор.Название as \'Название\'"}, Hidden=new string[] {
            "Вендор.Название"})]
    [MasterViewDefineAttribute("ПОE", "Вендор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class ПО : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fВерсия;
        
        private bool fFreeware;
        
        private IIS.Uchet.Вендор fВендор;
        
        private IIS.Uchet.РабочееМесто fРабочееМесто;
        
        // *** Start programmer edit section *** (ПО CustomMembers)

        // *** End programmer edit section *** (ПО CustomMembers)

        
        /// <summary>
        /// Freeware.
        /// </summary>
        // *** Start programmer edit section *** (ПО.Freeware CustomAttributes)

        // *** End programmer edit section *** (ПО.Freeware CustomAttributes)
        public virtual bool Freeware
        {
            get
            {
                // *** Start programmer edit section *** (ПО.Freeware Get start)

                // *** End programmer edit section *** (ПО.Freeware Get start)
                bool result = this.fFreeware;
                // *** Start programmer edit section *** (ПО.Freeware Get end)

                // *** End programmer edit section *** (ПО.Freeware Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПО.Freeware Set start)

                // *** End programmer edit section *** (ПО.Freeware Set start)
                this.fFreeware = value;
                // *** Start programmer edit section *** (ПО.Freeware Set end)

                // *** End programmer edit section *** (ПО.Freeware Set end)
            }
        }
        
        /// <summary>
        /// Версия.
        /// </summary>
        // *** Start programmer edit section *** (ПО.Версия CustomAttributes)

        // *** End programmer edit section *** (ПО.Версия CustomAttributes)
        [StrLen(255)]
        public virtual string Версия
        {
            get
            {
                // *** Start programmer edit section *** (ПО.Версия Get start)

                // *** End programmer edit section *** (ПО.Версия Get start)
                string result = this.fВерсия;
                // *** Start programmer edit section *** (ПО.Версия Get end)

                // *** End programmer edit section *** (ПО.Версия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПО.Версия Set start)

                // *** End programmer edit section *** (ПО.Версия Set start)
                this.fВерсия = value;
                // *** Start programmer edit section *** (ПО.Версия Set end)

                // *** End programmer edit section *** (ПО.Версия Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ПО.Название CustomAttributes)

        // *** End programmer edit section *** (ПО.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ПО.Название Get start)

                // *** End programmer edit section *** (ПО.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ПО.Название Get end)

                // *** End programmer edit section *** (ПО.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПО.Название Set start)

                // *** End programmer edit section *** (ПО.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ПО.Название Set end)

                // *** End programmer edit section *** (ПО.Название Set end)
            }
        }
        
        /// <summary>
        /// ПО.
        /// </summary>
        // *** Start programmer edit section *** (ПО.Вендор CustomAttributes)

        // *** End programmer edit section *** (ПО.Вендор CustomAttributes)
        [PropertyStorage(new string[] {
                "Вендор"})]
        [NotNull()]
        public virtual IIS.Uchet.Вендор Вендор
        {
            get
            {
                // *** Start programmer edit section *** (ПО.Вендор Get start)

                // *** End programmer edit section *** (ПО.Вендор Get start)
                IIS.Uchet.Вендор result = this.fВендор;
                // *** Start programmer edit section *** (ПО.Вендор Get end)

                // *** End programmer edit section *** (ПО.Вендор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПО.Вендор Set start)

                // *** End programmer edit section *** (ПО.Вендор Set start)
                this.fВендор = value;
                // *** Start programmer edit section *** (ПО.Вендор Set end)

                // *** End programmer edit section *** (ПО.Вендор Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Uchet.РабочееМесто.
        /// </summary>
        // *** Start programmer edit section *** (ПО.РабочееМесто CustomAttributes)

        // *** End programmer edit section *** (ПО.РабочееМесто CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РабочееМесто"})]
        public virtual IIS.Uchet.РабочееМесто РабочееМесто
        {
            get
            {
                // *** Start programmer edit section *** (ПО.РабочееМесто Get start)

                // *** End programmer edit section *** (ПО.РабочееМесто Get start)
                IIS.Uchet.РабочееМесто result = this.fРабочееМесто;
                // *** Start programmer edit section *** (ПО.РабочееМесто Get end)

                // *** End programmer edit section *** (ПО.РабочееМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПО.РабочееМесто Set start)

                // *** End programmer edit section *** (ПО.РабочееМесто Set start)
                this.fРабочееМесто = value;
                // *** Start programmer edit section *** (ПО.РабочееМесто Set end)

                // *** End programmer edit section *** (ПО.РабочееМесто Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПОE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПОE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПОE", typeof(IIS.Uchet.ПО));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ПО.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПО CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПО CustomAttributes)
    public class DetailArrayOfПО : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Uchet.DetailArrayOfПО members)

        // *** End programmer edit section *** (IIS.Uchet.DetailArrayOfПО members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПО by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПО.
        /// </summary>
        public DetailArrayOfПО(IIS.Uchet.РабочееМесто fРабочееМесто) : 
                base(typeof(ПО), ((ICSSoft.STORMNET.DataObject)(fРабочееМесто)))
        {
        }
        
        public IIS.Uchet.ПО this[int index]
        {
            get
            {
                return ((IIS.Uchet.ПО)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Uchet.ПО dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
