//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Uchet
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Филиал.
    /// </summary>
    // *** Start programmer edit section *** (Филиал CustomAttributes)

    // *** End programmer edit section *** (Филиал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФилиалE", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'"})]
    [View("ФилиалL", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'"})]
    public class Филиал : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (Филиал CustomMembers)

        // *** End programmer edit section *** (Филиал CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Филиал.Адрес CustomAttributes)

        // *** End programmer edit section *** (Филиал.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Филиал.Адрес Get start)

                // *** End programmer edit section *** (Филиал.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Филиал.Адрес Get end)

                // *** End programmer edit section *** (Филиал.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Филиал.Адрес Set start)

                // *** End programmer edit section *** (Филиал.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Филиал.Адрес Set end)

                // *** End programmer edit section *** (Филиал.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Филиал.Название CustomAttributes)

        // *** End programmer edit section *** (Филиал.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Филиал.Название Get start)

                // *** End programmer edit section *** (Филиал.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Филиал.Название Get end)

                // *** End programmer edit section *** (Филиал.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Филиал.Название Set start)

                // *** End programmer edit section *** (Филиал.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Филиал.Название Set end)

                // *** End programmer edit section *** (Филиал.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФилиалE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФилиалE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФилиалE", typeof(IIS.Uchet.Филиал));
                }
            }
            
            /// <summary>
            /// "ФилиалL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФилиалL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФилиалL", typeof(IIS.Uchet.Филиал));
                }
            }
        }
    }
}
